# Six node (five workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
containers:
  - name: registry
    image: registry:2
    ports:
      - containerPort: 5000
        hostPort: 5001
